### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by boltex** [CoenraadS/Bracket-Pair-Colorizer-2#264]
Extension cannot activate upon startup of vscode. I've had been using this for many months without any problems, I was using it a couple hours ago too, but now this morning it gives an error and does not activate. Was there an update or something?

Heres the errors i get in the output panel 

	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:918:348)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:887:754)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:884:63)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:524)
	at TextMateLoader.getNodeModule (/home/felix/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.1.1/out/src/textMateLoader.js:106:16)
	at TextMateLoader.loadOniguruma (/home/felix/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.1.1/out/src/textMateLoader.js:112:32)
	at new TextMateLoader (/home/felix/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.1.1/out/src/textMateLoader.js:19:31)
	at new Settings (/home/felix/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.1.1/out/src/settings.js:10:31)
	at new DocumentDecorationManager (/home/felix/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.1.1/out/src/documentDecorationManager.js:9:25)
	at activate (/home/felix/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.1.1/out/src/extension.js:6:37)
	at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:244)
	at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:787:909)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:786:960
	at async Promise.all (index 0)
	at async h.$activate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:793:297)

**Comment by mogzol** [comment]
Looks like it's due to the recent change to fix VS Code 1.45. What version of VS Code are you using?

**Comment by mogzol** [comment]
Hmm looks like my recent PR does break compatibility with previous versions of VS Code, I've put up a new PR to fix the issue (#265), but in the meantime if you click the settings button for this extension in VS Code's extension list and choose "Install Another Version" and downgrade to 0.0.29 then it should be fixed. Alternatively you could update VS Code to 1.45.

**Comment by quarthex** [comment]
Upgrade from 0.1.1 to 0.1.2 worked for me. 👍
VS Codium 1.44.2

**Comment by boltex** [comment]
@mogzol Yeah I'm still on 1.44. Indded, its a good idea to keep compatibilty for at least one or two previous version when trying to support new vscode features... some people do not update as soon as new vscode version are released. 

In the meantime i'll just reactivate the plugin in a day or two when I upgrade vscode to 1.45 :) 

In any case, thanks for your contributions to those open source tools! You rock!

**Comment by yunti** [comment]
hmm not sure if my issue is related, but I'm on vscode 1.45 and plugin version 0.1.2 and the plugin still doesn't work for me. reported in
